"""Alembic environment.

Two things worth knowing:

1. The URL comes from `src.core.config.settings`, never from alembic.ini, so the
   migrations and the running app can never point at different databases.
2. PostGIS creates internal tables (`spatial_ref_sys`) and its own indexes.
   `include_object` filters them out, otherwise every autogenerated migration
   tries to drop them.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import create_engine, pool

from alembic import context
from src.core.config import settings

# Importing the registry is what puts every model into Base.metadata. Without it
# autogenerate emits a migration that drops half the schema.
from src.db.models_registry import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Objects PostGIS owns. Ours to use, never ours to migrate.
POSTGIS_TABLES = {"spatial_ref_sys", "geography_columns", "geometry_columns", "raster_columns"}


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    if type_ == "table":
        return name not in POSTGIS_TABLES
    if type_ == "column":
        return getattr(obj.table, "name", None) not in POSTGIS_TABLES
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=settings.sync_database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(settings.sync_database_url, poolclass=pool.NullPool)
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
