"""area.boundary_source + populate geom/centroid from approximate polygons

FR-MAP-001 (approximate boundaries, authorised by decision #1 in the plan).
The `area` table existed since `0001_foundation` with `geom` and `centroid`
nullable (pending BRD OI-3). This migration adds `boundary_source` to
distinguish approximate from official data, then populates the three geo
columns using the WKT boundaries generated by `tools/gen_area_seed.py`.

`ST_PointOnSurface` rather than `ST_Centroid` because `ST_Centroid` can
land outside the polygon for non-convex or donut shapes; `ST_PointOnSurface`
is always guaranteed to be inside the surface (PostGIS docs §8.4).

Revision ID: 0011_area_boundaries
Revises: 0010_incident_report
Create Date: 2026-08-09

Refs: FR-MAP-001, FR-MAP-008
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_area_boundaries"
down_revision: str | None = "0010_incident_report"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# WKT boundaries keyed by area name. Inline here (not imported from seed_data/)
# so this migration is self-contained — a migration must not depend on a module
# that may change independently.
_AREA_WKT: list[tuple[str, str]] = [
    ("Area 1", "MULTIPOLYGON(((121.136 14.736, 121.136 14.734, 121.117531 14.734, 121.116521 14.73471, 121.115212 14.735416, 121.115212 14.735499, 121.115013 14.736, 121.136 14.736)))"),  # noqa: E501
    ("Area 2", "MULTIPOLYGON(((121.134 14.736, 121.115013 14.736, 121.114569 14.737118, 121.116886 14.738612, 121.118217 14.739442, 121.118045 14.740811, 121.11856 14.743924, 121.118259 14.745833, 121.118989 14.746995, 121.118731 14.749361, 121.121006 14.751519, 121.121349 14.75405, 121.121521 14.755918, 121.121821 14.757121, 121.122422 14.757495, 121.123538 14.758034, 121.124225 14.759279, 121.125383 14.760566, 121.127572 14.760981, 121.130233 14.761271, 121.133366 14.761479, 121.134 14.761524, 121.134 14.736)))"),  # noqa: E501
    ("Area 3", "MULTIPOLYGON(((121.133 14.734, 121.133 14.725737, 121.131359 14.724754, 121.131204 14.72353, 121.130651 14.722762, 121.129873 14.722186, 121.129407 14.721839, 121.128468 14.721683, 121.127695 14.721844, 121.126993 14.722093, 121.124933 14.72064, 121.123302 14.723089, 121.121929 14.724272, 121.121457 14.724874, 121.120877 14.726015, 121.120341 14.726949, 121.119998 14.727779, 121.119804 14.728485, 121.119311 14.729854, 121.118796 14.730269, 121.119268 14.731743, 121.118667 14.733216, 121.118646 14.733216, 121.117531 14.734, 121.133 14.734)), ((121.134 14.736, 121.134 14.761524, 121.136842 14.761728, 121.137764 14.761271, 121.139427 14.75985, 121.139299 14.759689, 121.138837 14.759259, 121.138183 14.758688, 121.137346 14.75819, 121.137335 14.757687, 121.138505 14.756976, 121.140398 14.755534, 121.143258 14.754201, 121.142088 14.753703, 121.142571 14.751809, 121.144137 14.750253, 121.146369 14.748219, 121.145961 14.746565, 121.146337 14.745548, 121.146519 14.744012, 121.145597 14.743037, 121.147056 14.740355, 121.147292 14.737304, 121.146384 14.736, 121.134 14.736)))"),  # noqa: E501
    ("Area 4", "MULTIPOLYGON(((121.133 14.734, 121.14 14.734, 121.14 14.73, 121.133 14.73, 121.133 14.734)))"),  # noqa: E501
    ("Area 5", "MULTIPOLYGON(((121.136 14.734, 121.136 14.736, 121.146384 14.736, 121.145747 14.735084, 121.145959 14.734, 121.146743 14.73, 121.14 14.73, 121.14 14.734, 121.136 14.734)))"),  # noqa: E501
    ("Area 6", "MULTIPOLYGON(((121.133 14.73, 121.146743 14.73, 121.147292 14.727198, 121.146256 14.727431, 121.146095 14.727073, 121.145629 14.726601, 121.145173 14.726627, 121.144738 14.726736, 121.143971 14.726669, 121.14351 14.726658, 121.142678 14.725891, 121.140339 14.725932, 121.139181 14.726492, 121.138451 14.725496, 121.136155 14.725766, 121.13483 14.725984, 121.134331 14.726534, 121.133 14.725737, 121.133 14.73)))"),  # noqa: E501
]


def upgrade() -> None:
    # 1. Add the boundary_source column.
    op.add_column(
        "area",
        sa.Column("boundary_source", sa.Text(), nullable=True),
    )
    op.create_check_constraint(
        "ck_area_boundary_source_valid",
        "area",
        "boundary_source IS NULL OR boundary_source IN ('official', 'approximate')",
    )

    # 2. Populate geom, centroid, and boundary_source for rows where geom IS NULL.
    #    Only touches rows that match by name and have no geometry yet — safe to
    #    re-run on a DB that already has official boundaries in some areas.
    conn = op.get_bind()
    for name, wkt in _AREA_WKT:
        conn.execute(
            sa.text(
                """
                UPDATE area
                SET
                    geom             = ST_GeomFromText(:wkt, 4326),
                    centroid         = ST_PointOnSurface(ST_GeomFromText(:wkt, 4326)),
                    boundary_source  = 'approximate'
                WHERE name = :name
                  AND geom IS NULL
                """
            ),
            {"wkt": wkt, "name": name},
        )


def downgrade() -> None:
    # Restore geom/centroid to NULL for approximate rows only, then drop the column.
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE area SET geom = NULL, centroid = NULL WHERE boundary_source = 'approximate'"
        )
    )
    op.drop_constraint("ck_area_boundary_source_valid", "area", type_="check")
    op.drop_column("area", "boundary_source")
