"""Generate seed_data/area_boundaries.py from dataset/derived/san_jose_areas_approx.geojson.

Usage:
    python tools/gen_area_seed.py

Outputs apps/api/src/seed_data/area_boundaries.py — WKT tuples so the API
image never depends on GeoJSON libraries or dataset files at runtime.
The derived GeoJSON is the source of truth; this script is the translator.

Stdlib only: json, pathlib. No geopandas, no shapely.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GEOJSON_PATH = REPO_ROOT / "dataset" / "derived" / "san_jose_areas_approx.geojson"
OUT_PATH = REPO_ROOT / "apps" / "api" / "src" / "seed_data" / "area_boundaries.py"


def coords_to_wkt_polygon(ring: list[list[float]]) -> str:
    """A single coordinate ring → WKT POLYGON string."""
    pairs = ", ".join(f"{lon} {lat}" for lon, lat in ring)
    return f"POLYGON(({pairs}))"


def multipolygon_to_wkt(geometry: dict) -> str:
    """GeoJSON MultiPolygon geometry → WKT MULTIPOLYGON string."""
    if geometry["type"] == "Polygon":
        # Promote to MultiPolygon for a uniform schema column type.
        rings = geometry["coordinates"]
        inner = ", ".join(f"({', '.join(f'{lon} {lat}' for lon, lat in ring)})" for ring in rings)
        return f"MULTIPOLYGON((({inner.lstrip('(').rstrip(')')}))"
    # Proper MultiPolygon
    parts = []
    for polygon in geometry["coordinates"]:
        rings = ", ".join(
            f"({', '.join(f'{lon} {lat}' for lon, lat in ring)})" for ring in polygon
        )
        parts.append(f"({rings})")
    return f"MULTIPOLYGON({', '.join(parts)})"


def main() -> None:
    with GEOJSON_PATH.open(encoding="utf-8") as fh:
        fc = json.load(fh)

    rows: list[tuple[str, str, str, str]] = []
    for feature in fc["features"]:
        props = feature["properties"]
        name = props["name"]
        code = props["code"]
        source = props.get("boundary_source", "approximate")
        wkt = multipolygon_to_wkt(feature["geometry"])
        rows.append((name, code, source, wkt))

    lines = [
        '"""Approximate area boundary seed data — generated by tools/gen_area_seed.py.',
        "",
        "DO NOT HAND-EDIT. Re-run `python tools/gen_area_seed.py` when the source",
        "GeoJSON changes (`dataset/derived/san_jose_areas_approx.geojson`).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# (name, code, boundary_source, wkt)",
        "AREA_BOUNDARIES: list[tuple[str, str, str, str]] = [",
    ]
    for name, code, source, wkt in rows:
        lines.append(f'    ({name!r}, {code!r}, {source!r}, {wkt!r}),')
    lines.append("]")
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
